apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-k8s-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-k8s-demo
  template:
    metadata:
      labels:
        app: flask-k8s-demo
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
      - name: flask-k8s-demo
        image: sachin293/flask-k8s-demo:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-k8s-service
spec:
  selector:
    app: flask-k8s-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
